blog/config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "devise/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    post 'approve/:id', to: 'devise/registrations#approve', as: 'approve'
    post 'revoke/:id', to: 'devise/registrations#revoke', as: 'revoke'
    get 'userhome/:id', to: 'users#home', as: 'home'
    get 'usersummary/:id', to: 'users#user_summary', as: 'user_summary'
    get 'managersummary', to: 'users#manager_summary', as: 'manager_summary'
    delete 'delete/users/:id', to: 'users#destroy', as: 'destroy'
    post 'upgrade/:id', to: 'users#upgrade', as: 'upgrade'
  end
  resources :users
  root to: "pois#index"
  resources :comment do
    post 'verify', to: 'comments#verify', as: 'verify'
  end
  resources :images
  resources :pois do
      delete 'delete/images/', to: 'images#destroy', as: 'destroy_image'
    resources :images
    resources :comments

  end

end

blog/app/models/user.rb
#Model representing a user.
#Ryan Pepin Drew Justus 2014
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :recoverable
  has_many :pois, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  do_not_validate_attachment_file_type :avatar
  has_attached_file :avatar, :default_url => "/images/missing.png", :url  => "/images/:class/:attachment/:id_partition/:style/:basename.:extension",
                    :path => "#{Rails.root}/public/images/:class/:attachment/:id_partition/:style/:basename.:extension",
                    :styles => {:thumbnail => '200x200#!', :medium => "400x400#!", :huge => "600x600#!"}
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates :first_name, presence: true, length: { minimum: 2}
  validates :last_name, presence: true, length: { minimum: 2}
  validates :email, length: { minimum: 5}
  validates :role, presence: true
  validates_format_of :email, :with => /\A.+@.+\..+\z/

  before_save :destroy_avatar?
  
  #Creates a new user if their account doesn't already exist, from facebook. Courtesy of oauth gem website.
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  #upgrades the user's role and sets their requested role back to blank.
  def upgrade_role
      self.role = self.requestedRole
      self.requestedRole = ""
  end
  #returns the default value of avatar_delete, 0
  def avatar_delete
    @avatar_delete ||= "0"
  end
  #sets the value of avatar delete to value
  #param(value) the value to set avatar delete to. 0/1
  def avatar_delete=(value)
    @avatar_delete = value
  end
  #Gets fields for creating a new user from facebook using oauth
  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.role = "User"
      user.avatar = URI.parse(auth.info.image) if (auth.info.image?)
    end
  end
  #Gets fields for creating a new user from google plus using oauth
  def self.find_for_google_oauth2(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.role = "User"
      user.avatar = URI.parse(auth.info.image) if (auth.info.image?)
    end
  end
  #Sets the verify field for this user to true.
  def verify
    self.verified = true
  end
  private

  def destroy_avatar?
    self.avatar.clear if @avatar_delete == "1"
  end

end

blog/app/controllers/users/omniauth_callbacks_controller.rb
#Class for allowing users to log in via facebook/google+
#Ryan Pepin Drew Justus 2014
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  #Allows a user to sign in via facebook
  #+@user+ the user signing in
  def facebook   
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  #Allows a user to sign in via google+
  #+@user+ the user signing in
  def google_oauth2
        @user = User.find_for_google_oauth2(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else#sign in with the user if the account exists or create one if it can, else take them to the register form.
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

blog/app/controllers/users_controller.rb
#Handles instances of the User class and makes them accesible to the view
#Ryan Pepin Drew Justus 2014
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:user_summary, :manager_summary]
  #Index displays all the users and any comments with images that have no been approved.
  #+@users+ all the users registered on the site
  #+@comments+ only comments with images where approved is false
  def index
    @users = User.all
    @comments = Comment.where("approved = ? and image_file_name IS NOT NULL", false);
  end

  #Destoys the given user
  #+@user+ the user being destroyed
  #precondition: current use role is admin
  #postcondition: selected user no longer exists
  def destroy
    if(current_user.role != "Admin")
      owns_this?(User.find(params[:id]))#precondition check
    end
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  #Displays a home page where a poi Manager can see all pois they own
  #+@user+ the user whose pois to show
  #+@pois+ all the pois belonging to @user
  #precondition: current_user is @user
  def home
    @user = User.find(params[:id])
    owns_this?(@user.id)#precondition check
    @pois = Poi.where("user_id = ?", @user[:id])
  end

  #Displays a summary for the selected user. Shows their pois and information
  #+@user+ the user to display a summary for
  #+@pois+ the pois owned by the user
  def user_summary
    @user = User.find(params[:id])
    @pois = Poi.where("user_id = ?", @user[:id])
  end

  #Displays a list of all verified poi managers and their website.
  #+@users+ all users whose role is poimanager and verified is true
  def manager_summary
      @users = User.all(:include => :pois)
      # @users = User.where("role = ? AND verified = ?", "POIManager", true)
      # @users += User.where("role = ? AND verified = ?", "PoiManager", true)
  end

  #upgrades a users role to the requested role
  #+@user+ the user being upgraded
  #precondition the current_user role is admin
  def upgrade
    if current_user.role != "Admin"
      render :file => 'public/422.html', :layout => false
    else
      @user = User.find(params[:id])
      @user.upgrade_role()
      @user.save
      redirect_to users_path
    end

  end
  private

  def owns_this?(user_id)
    unless (current_user.id == user_id)
      render :file => 'public/422.html', :layout => false
    end
  end

end

blog/app/views/users/destroy.html.erb
wtf

blog/app/views/users/home.html.erb
<% if user_signed_in? %>
<% if @user.verified%>
<br/>
<%= link_to 'Create Point', new_poi_path, id:"manage-create-point", class:"button-link" %>
<br/>
<% end %>
<% end %>
<br/>
Welcome <%= @user.first_name %>!
<br/>
<h1>Manage Points</h1>
<hr/>

<div class="contant-wrapper-min-width">
<table id="index_post_table">
	<% @pois.each do |poi| %>

	<tr class="posts">
		<td class="posts" id="post_image" width="20%"><%= image_tag poi.image.url(:thumbnail), class:"post-image", width:"250px"%></td>

		<td class="posts" id="post-content">
			<table width="100%", height="100%">
				<tr>
					<td>
						<%= link_to '', new_poi_image_path(poi), class: "edit-button", Id:"add-image-button"%>
						<%= link_to '', edit_poi_path(poi), class: "edit-button", Id:"edit" %> 
						<%= link_to '', poi_path(poi), class: "edit-button", Id:"delete",
						method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>	
					</tr>
		
				<tr>
					<td>
						<p id="post_title">
							<%= link_to poi.title, poi_path(poi), class:"post-link" %>
						</p>
						<p class="description">
						<br/>
							<strong><%= poi.description %></strong>
						<br/>
						</p>
		
						<p>
							<%= link_to User.find(poi.user_id).first_name + " " + User.find(poi.user_id).last_name, user_summary_path(poi.user_id), class:"artist-link"%>
						</p></br>
					</td>
				</tr>
			</table>
		</td>

		<td class="posts" id="post_map" width="15%"><br> Created:<br/> <%=(poi.created_at.to_formatted_s(:short) )%> <br/><br/> Updated:<br/> <%=poi.updated_at.to_formatted_s(:short)%> <br/><br/><%=(Comment.where("poi_id = ?", poi.id)).count%> comments</td>

		</td>
		
	</tr>

	<% end %>
</table>
</div>

<hr/>
<h1>&nbsp;</h1>
<br/>

blog/app/views/users/index.html.erb
<br/>
<h1>Manage Accounts</h1>
<hr/>

<div class="contant-wrapper-min-width">
	<table width="100%" id="manage-account-content">
		<tr>
			<th>Email</th>
			<th>Role</th>
			<th>Verified</th>
			<th>Requested role</th>
			<th></th>
		</tr>

		<% @users.each do |user| %>
		<tr>
			<td class="center"><%= user.email %></td>
			<td class="center"><%= user.role %></td>
			<td class="center"><%= user.verified%></td>
			<td class="center"><%= user.requestedRole%></td>
			<td class="center"><%= button_to 'Verify', approve_path(user.id), {:method => :post, :form_class => "approve"} %></td>
			<td class="center"><%= button_to 'Revoke', revoke_path(user.id), {:method => :post, :form_class => "revoke"} %></td>
			<td class="center"><%= button_to 'Upgrade', upgrade_path(user.id), {:method => :post, :form_class => "upgrade"} %></td>
			<td class="center"><%= button_to 'Delete', destroy_path(user.id), {:method => :delete, :form_class => "destroy"} %></td>

		</tr>
		<% end %>

	</table>
</div>

<hr/>
<h1>Manage Pictures</h1>
<hr/>

<div class="contant-wrapper-min-width">
<table width="100%" id="manage-account-content">
	<tr>
		<th>Picture</th>

		<th></th>
		<th></th>
	</tr>

	<% @comments.each do |comment|%>
	<tr>
		<td class="center"><%= image_tag comment.image.url(:thumbnail), width: "150px", class:"post-image"%></td>
		<td class="center"><%= comment.body%></td>

		<td class="center"><%= button_to 'Approve', comment_verify_path(comment.id), {:method => :post, :form_class => "approve_comment"} %></td>
		<td class="center"><%= button_to 'Delete', [comment.poi, comment], {:method => :delete, :form_class => "destroy"} %></td>

		<%end%>
	</tr>
</table>
</div>
<hr/>
<h1>&nbsp;</h1>
<br/>

blog/app/views/users/manager_summary.html.erb
<br/>
<h1>Artists</h1>
<hr/>
<div class="contant-wrapper-min-width">
<table width="100%" id="manage-account-content">
  <tr>
    <th id="artist-name-heading">Artist Name</th>
    <th>Artist Website</th>

  </tr>
 
<% @users.each do |user|	 %>     
  <tr><%if user.pois.count >= 1 %>
    <td ><%= link_to User.find(user.id).first_name + " " + User.find(user.id).last_name, user_summary_path(user.id), class:"artist-link"%>
</td>

    <td class="center"><%= user.private_web_url %></td> 

    </tr>
<%end%>
<% end %>
</table>
</div>

<hr/>
<h1>&nbsp;</h1>

<br />

blog/app/views/users/user_summary.html.erb
<%= stylesheet_link_tag    "manage", media: "all", "data-turbolinks-track" => true %>
<br />
<%= link_to 'Back', :back, class:"button-back"%>
<br />
<br />
<h1><%= @user.first_name%> <%= @user.last_name%></h1>
<hr />

<div class="contant-wrapper-min-width">
<table id="artist-content">
	<tr>
		<td width="25%"> <%= image_tag @user.avatar.url(:thumbnail), width:"250px", class:"post-image"%> </td>
		<td>
		<br />
		<%= @user.about_me%> <br/><br/> <%= link_to @user.private_web_url, @user.private_web_url%> </td>
	</tr>
</table>
</div>

<%if @pois.any?%>
<hr />
<h2>Points By Artist</h2>
<br />
<div class="contant-wrapper-min-width">
<table id="index_post_table">

	<% @pois.each do |poi| %>
	<tr class="posts">
		<td class="posts" id="post_image"><%= image_tag poi.image.url(:thumbnail), width: "250px", class:"post-image"%></td>

		<td class="posts">
		<p id="post_title">
			<%= link_to poi.title, poi_path(poi), class:"post-link" %>
		</p>
		<p class="description">
			<br/>
			<strong><%= poi.description %></strong>
			<br/>
		<p></p>
		<p>
			<%= link_to User.find(poi.user_id).first_name + " " + User.find(poi.user_id).last_name, user_summary_path(poi.user_id), class:"artist-link"%>
		</p></br></td>

		<td class="posts" id="post_map" width="15%"><br> Created:<br/> <%=(poi.created_at.to_formatted_s(:short) )%> <br/><br/> Updated:<br/> <%=poi.updated_at.to_formatted_s(:short)%> <br/><br/><%=(Comment.where("poi_id = ?", poi.id)).count%> comments</td>

		</td>
	</tr>
	<% end %>
</table>
</div>
<%end%>
<hr/>
<h1>&nbsp;</h1>
<br/>