blog/config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"
  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "devise/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    post 'approve/:id', to: 'devise/registrations#approve', as: 'approve'
    post 'revoke/:id', to: 'devise/registrations#revoke', as: 'revoke'
    get 'userhome/:id', to: 'users#home', as: 'home'
    get 'usersummary/:id', to: 'users#user_summary', as: 'user_summary'
    get 'managersummary', to: 'users#manager_summary', as: 'manager_summary'
    delete 'delete/users/:id', to: 'users#destroy', as: 'destroy'
    post 'upgrade/:id', to: 'users#upgrade', as: 'upgrade'
  end
  resources :users
  root to: "pois#index"
  resources :comment do
    post 'verify', to: 'comments#verify', as: 'verify'
  end
  resources :images
  resources :pois do
      delete 'delete/images/', to: 'images#destroy', as: 'destroy_image'
    resources :images
    resources :comments

  end

end

blog/app/models/image.rb
#Model of an image object. Is associated to a poi.
#Ryan Pepin Drew Justus 2014
class Image < ActiveRecord::Base
  has_attached_file :poi_image, :url  => "/images/:class/:attachment/:id_partition/:style/:basename.:extension",
                    :path => "#{Rails.root}/public/images/:class/:attachment/:id_partition/:style/:basename.:extension",
                    :styles => {:thumbnail => '200x200#!', :medium => "400x400#!", :huge => "600x600#!"}
  do_not_validate_attachment_file_type :poi_image
  validates_attachment_content_type :poi_image, :content_type => ['image/jpeg', 'image/png']
  validates_attachment_size :poi_image, :less_than => 5.megabytes 
  belongs_to :poi
  belongs_to :user
  validates :user_id, presence: true
  validates :poi_id, presence: true
  #Sets some inital parameters of the image object.
  #params(poi_id) the id of the poi object who owns the comment
  #params(user_id) the id of the user who owns the comment
  def setup(poi_id,user_id)
    self.poi_id = (poi_id)
    self.user_id = user_id
  end
end

blog/app/controllers/images_controller.rb
#Controller for creating/displaying/deleteing image objects
#Ryan Pepin Drew Justus 2014
class ImagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_PoiManager, only:[:create, :destroy]
  #Creates an instance of an image object
  #+@poi+ the poi the image(s) belongs to.
  #+@image+ the new instance of an image object
  #+@images+ all other images tied to the same poi_jd
  def new
    @poi = Poi.find(params[:poi_id])
    @image = Image.new
    @images = Image.where("poi_id = ?", params[:poi_id])
  end
  
  #Attempts to save the image object with the given parameters
  #+@poi+ the poi the image(s) belongs to.
  #+@images+ all images associated with the same poi
  #+@image+ the image to be saved
  #precondition: current_user.role == poi manager or admin. see before_filter
  def create
    @poi = Poi.find(params[:poi_id])
    @images = Image.where("poi_id = ?", params[:poi_id])
    @image = Image.create image_params
    @image.setup((params[:poi_id]), current_user.id)
    if @image.poi_image.url.include?("missing")
    @image.delete
    else if @image.save
        redirect_to new_poi_image_path(@image.poi_id)
      else
        redirect_to new_poi_image_path(@image.poi_id)
      end
    end
  end

  #destroys the selected image from the DB
  #+@image+ the image to be desroyed
  #precondition: current_user must own the image or be an admin
  def destroy
    @image = Image.find(params[:id])
    if(!owns_post?(@image.user_id) || current_user.role != "Admin")#precondition check
      render :file => 'public/422.html', :layout => false
    else
      @image.destroy
      redirect_to new_poi_image_path(Poi.find(@image.poi_id))
    end
  end
  private

  def image_params
    params.fetch(:image, {}).permit(:poi_id, :user_id, :poi_image)
  end

  def authenticate_PoiManager
    unless (((current_user.role == "PoiManager"|| current_user.role == "POIManager") && current_user.verified == true) || current_user.role == "Admin")
      @error = "Must be verified."
      render :file => 'public/422.html', :layout => false
    end
  end

  def owns_post?(user_id)
    unless (current_user.id == user_id)
    return false
    end
    return true
  end
end

blog/app/helpers/images_helper.rb
module ImagesHelper
end

blog/app/views/images/_form.html.erb
<%= form_for @image, :url => poi_images_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :poi_image %>
  <%= form.submit "Add"%>
	

<% end %>

blog/app/views/images/create.html.erb
	
	<br/>
	<%= link_to 'Back to Poi', poi_path(@poi), class:"button-back"%>
	<br/>
	<br/>
	<h1>Add Image</h1>
	 <hr/>
	 
	<%= render 'form' %>
	
	<hr />

	<h1>&nbsp;</h1>
	<br/>
			<th></th>
		<th></th>
	</tr>

<h1>Manage Images</h1>
<hr/>
<table width="100%" id="manage-account-content">
	<tr>
		<th>Picture</th>

		<th></th>
		<th></th>
	</tr>

	<% @images.each do |image|%>
	<tr>
		<td class="center"><%= image_tag image.poi_image.url(:thumbnail), width: "150px", class:"post-image"%></td>

		<td class="center"><%= button_to 'Delete', image_path(image.id), {:method => :delete, :form_class => "destroy"} %></td>

		<%end%>
	</tr>
</table>
<hr/>
<h1>&nbsp;</h1>
<br/>

blog/app/views/images/new.html.erb
	
	<br/>
	<%= link_to 'Back', poi_path(@poi), class:"button-back"%>
	<br/>
	<br/>
	<h1>Add Image</h1>
	 <hr/>
	 
	<%= render 'form' %>
	
	<hr />

<%if @images.any?%>
<h1>Manage Images</h1>
<hr/>
<div class="contant-wrapper-min-width">
<table width="100%" id="manage-account-content">
	<tr>
		<th>Picture</th>

		<th></th>
		<th></th>
	</tr>

	<% @images.each do |image|%>
	<tr>
		<td class="center"><%= image_tag image.poi_image.url(:thumbnail), width: "150px", class:"post-image"%></td>

		<td class="center"><%= button_to 'Delete', image_path(image.id), {:method => :delete, :form_class => "destroy"} %></td>

		<%end%>
	</tr>
</table>
</div>
<hr/>
<%end%>
<h1>&nbsp;</h1>
<br/>